export const townshipOptions = [
    { value: "North Dagon", label: "North Dagon" },
    { value: "South Dagon", label: "South Dagon" },
    { value: "East Dagon", label: "East Dagon" },
    { value: "West Dagon", label: "West Dagon" },
    { value: "Dagon Myothit", label: "Dagon Myothit" },
    { value: "Dawbon", label: "Dawbon" },
    { value: "Mingalar Taung Nyunt", label: "Mingalar Taung Nyunt" },
    { value: "Tamwe", label: "Tamwe" },
    { value: "Bahan", label: "Bahan" },
    { value: "Kyauktada", label: "Kyauktada" },
    { value: "Pabedan", label: "Pabedan" },
    { value: "Lanmadaw", label: "Lanmadaw" },
    { value: "Latha", label: "Latha" },
    { value: "Ahlone", label: "Ahlone" },
    { value: "Kyimyindine", label: "Kyimyindine" },
    { value: "Sanchaung", label: "Sanchaung" },
    { value: "Hlaing", label: "Hlaing" },
    { value: "Kamayut", label: "Kamayut" },
    { value: "Mayangone", label: "Mayangone" },
    { value: "Yankin", label: "Yankin" },
    { value: "Thingangyun", label: "Thingangyun" },
    { value: "North Okkalapa", label: "North Okkalapa" },
    { value: "South Okkalapa", label: "South Okkalapa" },
    { value: "Shwepyitha", label: "Shwepyitha" },
    { value: "Hmawbi", label: "Hmawbi" },
    { value: "Hlegu", label: "Hlegu" },
    { value: "Taikkyi", label: "Taikkyi" },
    { value: "Htantabin", label: "Htantabin" },
    { value: "Zay", label: "Zay" },
  ];